#!/bin/sh

# Copy my config files to my backup folder

folder=$HOME/box/configbackups

dotfiles=".bash_profile .bashrc .profile .inputrc .mblaze .nexrc .tmux.conf .virc .xinitrc .config/isyncrc"
config="colors fontconfig git imv msmtp zathura"
src="dmenu dwm st"

for d in config home src ssh; do mkdir -p "$folder/$d"; done

# copy

for i in $dotfiles;
	do cp -Rf "$HOME"/"$i" "$folder"/home/
done

for i in $config
	do cp -Rf "$HOME"/.config/"$i" "$folder"/config/
done

for i in $src
	do mkdir "$folder"/src/"$i"
	cp -f "$HOME"/.local/src/"$i"/*.{c,h} "$folder"/src/"$i"/
done

cp "$HOME"/.ssh/config "$folder"/ssh/
