#!/bin/sh

# A bookmark browser based on dmenu

# Requires: dmenu-filepicker, open-url

#dir=$XDG_DATA_HOME/bookmarks
dir=$HOME/Dropbox/bookmarks # TODO: change it when I have a better sync system

echo "$(dmenu-filepicker $dir)" | while read line; do
	cat "$line"
done | xargs open-url
