#!/bin/sh

# A bookmark browser based on dmenu

# Requires: dmenu-filepicker, open-url

#dir=$XDG_DATA_HOME/bookmarks
dir=$HOME/Dropbox/bookmarks # TODO: change it when I have a better sync system

cat $(dmenu-filepicker "$dir") | xargs open-url
