#!/bin/sh

# Select mail alias via dmenu
# The email address must be the second word in a line of $aliasfile
# Requires: dmenu (or similar)

menu=${MENU:-dmenu}
menuopts="-l 20"
aliasfile="$HOME/.mblaze/aliases"

$menu $menuopts <"$aliasfile" | awk '{print $NF}' 
