#!/bin/sh

# A bookmark browser based on dmenu

# Usage: dmenu-bookmarks [picker options...]

# Requires: dmenu-filepicker (or similar), open-url

dir=$HOME/box/bookmarks
picker="dmenu-filepicker"

echo "$($picker "$@" $dir)" | while read line; do
	cat "$line"
done | xargs open-url
