#!/bin/sh

# Toggle "do not disturbe" mode with dunst
# Requires: dunst, notify-send

if [ "$(dunstctl is-paused)" = "false" ]; then
	notify-send -t 3000 "Notifications: OFF" "Notifications will be hidden"
	sleep 3
	dunstctl set-paused true
else
	dunstctl set-paused false
	notify-send -t 3000 "Notifications: ON" "Notifications reactivated"
fi

