#!/bin/sh

# Script based on nissy (see https://nissy.tronto.net) to practice FMC

# Usage: practice [htr]

usage() {
	echo "Usage: practice [htr]"
}

htr() {
	while true; do
		scr="$(nissy scramble dr)"
		echo "$scr"
		read -r x
		nissy solve -o htr "$scr"
		read -r x
	done
}

if [ -z "$1" ]; then
	usage
	exit 1
fi

case "$1" in
	htr)
		htr
		;;
	*)
		usage
		exit 1
		;;
esac
