#!/bin/sh

# One-liner to upload stuff to my webserver

srv=tronto.net
dir=$(tr -cd 'a-z0-9' < /dev/random | fold -w 8 | head -n 1)
htp=https://share.tronto.net/$dir
pth=/var/www/htdocs/share.tronto.net/$dir
url=$srv:$pth

ssh tronto.net mkdir "$pth"
scp "$@" "$url"/
for i in "$@"; do echo "$htp/$i"; done
