#!/bin/sh

# Opens google translate

translator="https://translate.google.com/"
from=$1
to=$2

shift 2
text=$(echo $@ | sed 's/ /\%20/g')
open-url "${translator}?sl=${from}&tl=${to}&text=${text}&op=translate"
