#!/bin/sh

# Simple trash management. Files are moved to a directory named with the
# current date.

# Usage: trash [rm FILE(s)|ls|empty]

# ksh completion
# set -A complete_trash_1 rm ls empty

trashfolder=$XDG_DATA_HOME/mytrash

usage() {
	echo "Usage: trash [rm FILES... | ls | empty]"
}

if [ -z "$1" ]; then
	usage
	exit 1
fi

case "$1" in
	empty)
		# little check
		if [ -n "$trashfolder" ]; then
			rm -rf "${trashfolder:?}"/*
		fi
		;;
	ls)
		ls "$trashfolder"
		;;
	rm)
		curdir=$(pwd | sed 's|.*/||')
		thisfolder="$trashfolder/$(date +'%Y-%m-%d-%s')-$curdir"
		mkdir -p "$thisfolder"
		shift 1
		mv "$@" "$thisfolder"
		;;
		
	*)
		usage
		exit 1
		;;
esac
