#!/bin/sh

# Perform a web search

browser=${BROWSER:-firefox}
searchengine="https://duckduckgo.com/?q="
# For google: https://www.google.com/search?q=

arg=$(echo "$@" | sed 's/ /\+/g')
[ -n "$arg" ] && spawn "$browser" "${searchengine}$arg"
