#!/bin/sh

# Set a random background from the wallpapers folder and notify about it
# Requires: xwallpaper (or feh), notify-send or similar (optional)

#notify=notify-send
notify="notify push"

folder=~/pictures/wallpapers
pic=$(ls $folder | sort -R | head -1)

# Alternative: use feh
#feh --bg-fill --no-fehbg $folder/$pic
xwallpaper --zoom $folder/$pic

# Uncomment to notify
#$notify "Background of the day" $pic
