#!/bin/sh

# Select mail alias via dmenu
# The email address must be the second word in a line of $aliasfile
# Requires: dmenu (or similar)

# Usage: dmenu-mail-aliases [-m menu]

usage() {
	echo "Usage: dmenu-mail-aliases [-m MENU]"
}

menu="dmenu -l 20"
aliasfile="$HOME/.mblaze/aliases"

while getopts "m:" opt; do
	case "$opt" in
		m)
			menu="$OPTARG"
			;;
		*)
			usage
			exit 1
			;;
		esac
done
shift $((OPTIND - 1))

$menu <"$aliasfile" | awk '{print $NF}' 
